### PR TITLE
cmdstanr and posterior updates

### PR DESCRIPTION
**Pull request by n-kall**
This modifies the cmdstanfit method to use the soon to be merged updated `unconstrain_draws` method.
Also updates the pareto_smooth function to use latest option `are_log_weights` so the weights don't need to be exponentiated first.

Addresses #8

### CODE REVIEW

**Comment by topipa** [comment]
@n-kall I think the changes in this PR were introduced in https://github.com/topipa/iwmm/pull/14, and we are now using the simpler form `udraws <- x$unconstrain_draws(format = "draws_matrix")`. Can this be closed, or is there something I missed?

**Comment by n-kall** [comment]
This PR also has updates using the new `are_log_weights =TRUE` for pareto smoothing, which could be added. I can look again next week, or you can check if this PR can be selectively merged in the meantime

**Comment by topipa** [comment]
Those were also added already. In hindsight it would have been much clearer to merge those changes in separate PRs. I'll try to have smaller and better separated PRs going forward.

I actually tried to pull the changes in this branch into the current main, and there does not seem to be any meaningful changes left (see [here](https://github.com/topipa/iwmm/compare/main...posterior-updates)), unless I missed something in solving merge conflicts.

**Comment by n-kall** [comment]
Great! Yeah I realised that I shouldn't have put these in the same PR. I didn't realise it would be hanging for so long due to delayed posterior release, but we eventually manages to get that on CRAN

**Comment by topipa** [comment]
Yeah the delay complicated things. But good that it's now clear, I will close this one.

**Pull request closed without merging**
